//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SystemCenter.CrossPlatform.ClientLibrary.ClientTasks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SystemCenter.CrossPlatform.ClientLibrary.ClientTasks.Properties.Resourc" +
                            "es", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent cannot be null.
        /// </summary>
        internal static string ChangeManagedByResult_AgentNull {
            get {
                return ResourceManager.GetString("ChangeManagedByResult_AgentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The criteria must be specified..
        /// </summary>
        internal static string DiscoveryResult_Criteria_NULL {
            get {
                return ResourceManager.GetString("DiscoveryResult_Criteria_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A discovery result must be specified..
        /// </summary>
        internal static string InstallAgentResult_InstallAgentResult_A_discovery_result_must_be_specified {
            get {
                return ResourceManager.GetString("InstallAgentResult_InstallAgentResult_A_discovery_result_must_be_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string IPRange {
            get {
                return ResourceManager.GetString("IPRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied IP range exceeds the maximum range of 1000 addresses..
        /// </summary>
        internal static string IPRange_TooLarge {
            get {
                return ResourceManager.GetString("IPRange_TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be empty..
        /// </summary>
        internal static string ScopeValidation_AddressIsEmpty {
            get {
                return ResourceManager.GetString("ScopeValidation_AddressIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided Discovery Scope value is invalid. 
        ///The value needs to be either a valid IP address, a valid DNS name or two valid IP addresses separated by a dash (&apos;-&apos;)..
        /// </summary>
        internal static string ScopeValidation_AddressIsInvalid {
            get {
                return ResourceManager.GetString("ScopeValidation_AddressIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name cannot be empty..
        /// </summary>
        internal static string ScopeValidation_HostnameIsEmpty {
            get {
                return ResourceManager.GetString("ScopeValidation_HostnameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name has an invalid format..
        /// </summary>
        internal static string ScopeValidation_HostnameIsInvalid {
            get {
                return ResourceManager.GetString("ScopeValidation_HostnameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address cannot be empty..
        /// </summary>
        internal static string ScopeValidation_IPIsEmpty {
            get {
                return ResourceManager.GetString("ScopeValidation_IPIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IPv4 or IPv6 address entered..
        /// </summary>
        internal static string ScopeValidation_IPIsInvalid {
            get {
                return ResourceManager.GetString("ScopeValidation_IPIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End address cannot be empty..
        /// </summary>
        internal static string ScopeValidation_RangeEndIsEmpty {
            get {
                return ResourceManager.GetString("ScopeValidation_RangeEndIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End address is not a valid IPv4 or IPv6 address..
        /// </summary>
        internal static string ScopeValidation_RangeEndIsInvalid {
            get {
                return ResourceManager.GetString("ScopeValidation_RangeEndIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start address cannot be empty..
        /// </summary>
        internal static string ScopeValidation_RangeStartIsEmpty {
            get {
                return ResourceManager.GetString("ScopeValidation_RangeStartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start address is not a valid IPv4 or IPv6 address..
        /// </summary>
        internal static string ScopeValidation_RangeStartIsInvalid {
            get {
                return ResourceManager.GetString("ScopeValidation_RangeStartIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start and end address formats are inconsistent..
        /// </summary>
        internal static string ScopeValidation_RangeValuesInconsistent {
            get {
                return ResourceManager.GetString("ScopeValidation_RangeValuesInconsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SSH port value must be between 1 and 65535..
        /// </summary>
        internal static string SSH_Port_Limitations {
            get {
                return ResourceManager.GetString("SSH_Port_Limitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An agent must be specified..
        /// </summary>
        internal static string UnmanageResult_Agent_Not_Specified {
            get {
                return ResourceManager.GetString("UnmanageResult_Agent_Not_Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hostname must be specified..
        /// </summary>
        internal static string UpdateResult_UpdateResult_A_hostname_must_be_specified {
            get {
                return ResourceManager.GetString("UpdateResult_UpdateResult_A_hostname_must_be_specified", resourceCulture);
            }
        }
    }
}
