//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.250
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SystemCenter.CrossPlatform.ClientLibrary.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SystemCenter.CrossPlatform.ClientLibrary.Common.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A management object with display name {0} could not be found..
        /// </summary>
        internal static string ManagedObjectNotFoundMessage {
            get {
                return ResourceManager.GetString("ManagedObjectNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property named {0} could not be found..
        /// </summary>
        internal static string ManagedObjectPropertyNotFoundMessage {
            get {
                return ResourceManager.GetString("ManagedObjectPropertyNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relationships for the management object {0} could not be found..
        /// </summary>
        internal static string ManagedObjectRelationshipNotFoundMessage {
            get {
                return ResourceManager.GetString("ManagedObjectRelationshipNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Run As account is identified with ID = .
        /// </summary>
        internal static string ManagementGroupConnection_GetScxRunAsAccount {
            get {
                return ResourceManager.GetString("ManagementGroupConnection_GetScxRunAsAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type named {0} could not be found in any imported management pack..
        /// </summary>
        internal static string MPTypeNotFoundMessage {
            get {
                return ResourceManager.GetString("MPTypeNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one relationship type is expected..
        /// </summary>
        internal static string RelationshipObjectFactory_CreateRelationshipObject_Only_one_relationship_type {
            get {
                return ResourceManager.GetString("RelationshipObjectFactory_CreateRelationshipObject_Only_one_relationship_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relationship type named {0} could not be found in any imported management pack..
        /// </summary>
        internal static string RelationshipTypeNotFoundMessage {
            get {
                return ResourceManager.GetString("RelationshipTypeNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key and account ID do not match..
        /// </summary>
        internal static string ScxCredentialRef_RunAsAcount_Key_and_account_ID_do_not_match {
            get {
                return ResourceManager.GetString("ScxCredentialRef_RunAsAcount_Key_and_account_ID_do_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credential {0} is already managed by Operations Manager .
        /// </summary>
        internal static string SCXRunAsAccountFactory_CreateRunAsAcccountRef_The_credential__0__is_already_managed_by_Operations_Manager {
            get {
                return ResourceManager.GetString("SCXRunAsAccountFactory_CreateRunAsAcccountRef_The_credential__0__is_already_manag" +
                        "ed_by_Operations_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account cannot be empty..
        /// </summary>
        internal static string SCXRunAsAccountFactory_DeleteScxRunAsAccount_Account_cannot_be_empty {
            get {
                return ResourceManager.GetString("SCXRunAsAccountFactory_DeleteScxRunAsAccount_Account_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCX Run As Account with ID = .
        /// </summary>
        internal static string SCXRunAsAccountFactory_GetScxRunAsAccount {
            get {
                return ResourceManager.GetString("SCXRunAsAccountFactory_GetScxRunAsAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  cannot be found..
        /// </summary>
        internal static string SCXRunAsAccountFactory_GetScxRunAsAccount__cannot_be_found {
            get {
                return ResourceManager.GetString("SCXRunAsAccountFactory_GetScxRunAsAccount__cannot_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not the type of basic authentication..
        /// </summary>
        internal static string SCXRunAsAccountFactory_UpdateScxRunAsAccount_Account_is_not_the_type_of_basic_auth {
            get {
                return ResourceManager.GetString("SCXRunAsAccountFactory_UpdateScxRunAsAccount_Account_is_not_the_type_of_basic_aut" +
                        "h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null argument cannot be used for updating Run As account..
        /// </summary>
        internal static string SCXRunAsAccountFactory_UpdateScxRunAsAccount_Null_argument_cannot_be_used_for_updating_RunAs_account {
            get {
                return ResourceManager.GetString("SCXRunAsAccountFactory_UpdateScxRunAsAccount_Null_argument_cannot_be_used_for_upd" +
                        "ating_RunAs_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task invocation failed with error code {0}. Error message was: {1}.
        /// </summary>
        internal static string TaskInvocationExceptionMessage {
            get {
                return ResourceManager.GetString("TaskInvocationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task named {0} could not be found.  Ensure that you have imported the lastest version of the management packs..
        /// </summary>
        internal static string TaskNotFoundMessage {
            get {
                return ResourceManager.GetString("TaskNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} derived types of class {1} in imported management packs. Expected 1..
        /// </summary>
        internal static string UniqueDerivedTypeNotFoundMessage {
            get {
                return ResourceManager.GetString("UniqueDerivedTypeNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkFlow was cancelled by the user..
        /// </summary>
        internal static string WorkFlowCancelledMessage {
            get {
                return ResourceManager.GetString("WorkFlowCancelledMessage", resourceCulture);
            }
        }
    }
}
